"""Conservative location enrichment for PAIMANA projects.

Detects clearly identifiable Indian state names and unambiguous city/place
names inside a project name. A state is assigned only when every location
hint found in the name points to the same single state. When the match is
not clear the values fall back to "Location Not Specified".

Districts are populated only when a single, unambiguous city is detected and
that city name is also its district (e.g. Chennai, Patna, Indore).
"""
import re

UNSPECIFIED = "Location Not Specified"

# Canonical state names follow the naming used by the @react-map/india
# front-end library so risk heat-map regions line up with DB rows.
STATE_ALIASES = {
    # full / explicit names
    "andhra pradesh": "Andhra Pradesh",
    "arunachal pradesh": "Arunachal Pradesh",
    "assam": "Assam",
    "bihar": "Bihar",
    "chhattisgarh": "Chhattisgarh",
    "goa": "Goa",
    "gujarat": "Gujarat",
    "haryana": "Haryana",
    "himachal pradesh": "Himachal Pradesh",
    "himachal": "Himachal Pradesh",
    "jharkhand": "Jharkhand",
    "karnataka": "Karnataka",
    "kerala": "Kerala",
    "madhya pradesh": "Madhya Pradesh",
    "maharashtra": "Maharashtra",
    "manipur": "Manipur",
    "meghalaya": "Meghalaya",
    "mizoram": "Mizoram",
    "nagaland": "Nagaland",
    "odisha": "Odisha",
    "punjab": "Punjab",
    "rajasthan": "Rajasthan",
    "sikkim": "Sikkim",
    "tamil nadu": "Tamil Nadu",
    "telangana": "Telangana",
    "tripura": "Tripura",
    "uttar pradesh": "Uttar Pradesh",
    "uttarakhand": "Uttarakhand",
    "west bengal": "West Bengal",
    "ladakh": "Ladakh",
    "jammu and kashmir": "Jammu and Kashmir",
    "jammu & kashmir": "Jammu and Kashmir",
    "jammu": "Jammu and Kashmir",
    "kashmir": "Jammu and Kashmir",
    "delhi": "Delhi",
    "new delhi": "Delhi",
    "andaman and nicobar islands": "Andaman and Nicobar Islands",
    "andaman": "Andaman and Nicobar Islands",
    "nicobar": "Andaman and Nicobar Islands",
    "puducherry": "Puducherry",
    "pondicherry": "Puducherry",
    "chandigarh": "Chandigarh",
    # abbreviations / common typos present in the source CSV
    "j&k": "Jammu and Kashmir",
    "mp": "Madhya Pradesh",
    "u.p": "Uttar Pradesh",
    "wb": "West Bengal",
    "jhrkhand": "Jharkhand",
    "kanataka": "Karnataka",
    "rajastha": "Rajasthan",
    "andhrapradesh": "Andhra Pradesh",
    "tamilnadu": "Tamil Nadu",
    # state abbreviations, used only in short program/appendix-style names
    "arp": "Arunachal Pradesh",
    "ktk": "Karnataka",
    "ngl": "Nagaland",
    "mnp": "Manipur",
    "mgh": "Meghalaya",
    "mzm": "Mizoram",
    "trp": "Tripura",
    "ani": "Andaman and Nicobar Islands",
    "lad": "Ladakh",
    "skm": "Sikkim",
    "ukd": "Uttarakhand",
    "dnh": "Dadra and Nagar Haveli",
    "py": "Puducherry",
    "rj": "Rajasthan",
}

# token -> (state, district).  district is only set when the token is an
# unambiguous city whose name equals its district.  Entries containing a
# space are matched as plain substrings; all others as whole words.
PLACES = {
    # Andhra Pradesh
    "rajahmundry": ("Andhra Pradesh", None),
    "kadapa": ("Andhra Pradesh", None),
    "vijayawada": ("Andhra Pradesh", None),
    "kurnool": ("Andhra Pradesh", "Kurnool"),
    "nandyal": ("Andhra Pradesh", "Nandyal"),
    "renigunta": ("Andhra Pradesh", None),
    "visakhapatnam": ("Andhra Pradesh", "Visakhapatnam"),
    "tirupati": ("Andhra Pradesh", "Tirupati"),
    "guntur": ("Andhra Pradesh", "Guntur"),
    "nellore": ("Andhra Pradesh", None),
    "eluru": ("Andhra Pradesh", "Eluru"),
    "kakinada": ("Andhra Pradesh", "Kakinada"),
    "polavaram": ("Andhra Pradesh", None),
    "visakh": ("Andhra Pradesh", None),
    # Arunachal Pradesh
    "itanagar": ("Arunachal Pradesh", None),
    "tawang": ("Arunachal Pradesh", None),
    "hunli": ("Arunachal Pradesh", None),
    "hayuliang": ("Arunachal Pradesh", None),
    "pasighat": ("Arunachal Pradesh", None),
    # Assam
    "guwahati": ("Assam", None),
    "silchar": ("Assam", None),
    "dibrugarh": ("Assam", "Dibrugarh"),
    "jorhat": ("Assam", "Jorhat"),
    "tezpur": ("Assam", None),
    "dhubri": ("Assam", "Dhubri"),
    "barpeta": ("Assam", "Barpeta"),
    "majuli": ("Assam", "Majuli"),
    "bilasipara": ("Assam", None),
    "jhanji": ("Assam", None),
    "demow": ("Assam", None),
    "numaligarh": ("Assam", None),
    "baghjan": ("Assam", None),
    "moran": ("Assam", None),
    "gauripur": ("Assam", None),
    # Bihar
    "patna": ("Bihar", "Patna"),
    "bihta": ("Bihar", None),
    "gaya": ("Bihar", "Gaya"),
    "bhagalpur": ("Bihar", "Bhagalpur"),
    "munger": ("Bihar", "Munger"),
    "darbhanga": ("Bihar", "Darbhanga"),
    "begusarai": ("Bihar", "Begusarai"),
    "muzaffarpur": ("Bihar", "Muzaffarpur"),
    "siwan": ("Bihar", "Siwan"),
    "chhapra": ("Bihar", None),
    "chapra": ("Bihar", None),
    "sitamarhi": ("Bihar", "Sitamarhi"),
    "samastipur": ("Bihar", "Samastipur"),
    "madhubani": ("Bihar", "Madhubani"),
    "saharsa": ("Bihar", "Saharsa"),
    "supaul": ("Bihar", "Supaul"),
    "sheohar": ("Bihar", "Sheohar"),
    "araria": ("Bihar", "Araria"),
    "hajipur": ("Bihar", None),
    "danapur": ("Bihar", None),
    "biharsharif": ("Bihar", None),
    "buxar": ("Bihar", "Buxar"),
    "jamui": ("Bihar", "Jamui"),
    "barauni": ("Bihar", None),
    "bakhtiyarpur": ("Bihar", None),
    "bhabhua": ("Bihar", None),
    "gopalganj": ("Bihar", "Gopalganj"),
    "nabinagar": ("Bihar", None),
    "champaran": ("Bihar", None),
    # Chhattisgarh
    "raipur": ("Chhattisgarh", "Raipur"),
    "bhilai": ("Chhattisgarh", "Bhilai"),
    "korba": ("Chhattisgarh", "Korba"),
    "ambikapur": ("Chhattisgarh", None),
    "jagdalpur": ("Chhattisgarh", None),
    "rajnandgaon": ("Chhattisgarh", "Rajnandgaon"),
    "dongarhgarh": ("Chhattisgarh", None),
    "durg": ("Chhattisgarh", "Durg"),
    "kondagaon": ("Chhattisgarh", "Kondagaon"),
    "dantewada": ("Chhattisgarh", "Dantewada"),
    "kanker": ("Chhattisgarh", "Kanker"),
    "mahasamund": ("Chhattisgarh", "Mahasamund"),
    "bastar": ("Chhattisgarh", None),
    "sukma": ("Chhattisgarh", "Sukma"),
    "narayanpur": ("Chhattisgarh", "Narayanpur"),
    "pathalgaon": ("Chhattisgarh", None),
    "dharamjaigarh": ("Chhattisgarh", None),
    "sipat": ("Chhattisgarh", None),
    # Delhi
    "delhi": ("Delhi", None),
    # Goa
    "cansaulim": ("Goa", None),
    "chandorgaon": ("Goa", None),
    # Gujarat
    "ahmedabad": ("Gujarat", "Ahmedabad"),
    "surat": ("Gujarat", "Surat"),
    "vadodara": ("Gujarat", "Vadodara"),
    "rajkot": ("Gujarat", "Rajkot"),
    "jamnagar": ("Gujarat", "Jamnagar"),
    "bhavnagar": ("Gujarat", "Bhavnagar"),
    "gandhinagar": ("Gujarat", "Gandhinagar"),
    "mehsana": ("Gujarat", "Mehsana"),
    "patan": ("Gujarat", "Patan"),
    "palanpur": ("Gujarat", None),
    "bhuj": ("Gujarat", None),
    "kutch": ("Gujarat", None),
    "mundra": ("Gujarat", None),
    "kandla": ("Gujarat", None),
    "khavda": ("Gujarat", None),
    "dholera": ("Gujarat", None),
    "keshod": ("Gujarat", None),
    "bharuch": ("Gujarat", "Bharuch"),
    "valsad": ("Gujarat", "Valsad"),
    "navsari": ("Gujarat", "Navsari"),
    "anand": ("Gujarat", "Anand"),
    "sanand": ("Gujarat", None),
    "kalol": ("Gujarat", None),
    "porbandar": ("Gujarat", "Porbandar"),
    "junagadh": ("Gujarat", "Junagadh"),
    "panchmahal": ("Gujarat", None),
    "dahod": ("Gujarat", "Dahod"),
    "godhra": ("Gujarat", None),
    "sabarkantha": ("Gujarat", None),
    "banaskantha": ("Gujarat", None),
    "morbi": ("Gujarat", "Morbi"),
    "amreli": ("Gujarat", "Amreli"),
    "shamlaji": ("Gujarat", None),
    "idar": ("Gujarat", None),
    # Haryana
    "gurugram": ("Haryana", "Gurugram"),
    "gurgaon": ("Haryana", "Gurugram"),
    "faridabad": ("Haryana", "Faridabad"),
    "rohtak": ("Haryana", "Rohtak"),
    "panipat": ("Haryana", "Panipat"),
    "hisar": ("Haryana", "Hisar"),
    "karnal": ("Haryana", "Karnal"),
    "sonipat": ("Haryana", "Sonipat"),
    "ambala": ("Haryana", "Ambala"),
    "kurukshetra": ("Haryana", "Kurukshetra"),
    "kaithal": ("Haryana", "Kaithal"),
    "jind": ("Haryana", "Jind"),
    "rewari": ("Haryana", "Rewari"),
    "panchkula": ("Haryana", "Panchkula"),
    "palwal": ("Haryana", "Palwal"),
    "dabwali": ("Haryana", None),
    # Himachal Pradesh
    "shimla": ("Himachal Pradesh", "Shimla"),
    "mandi": ("Himachal Pradesh", "Mandi"),
    "kangra": ("Himachal Pradesh", "Kangra"),
    "kullu": ("Himachal Pradesh", "Kullu"),
    "una": ("Himachal Pradesh", "Una"),
    "baddi": ("Himachal Pradesh", None),
    # Jammu and Kashmir
    "jammu": ("Jammu and Kashmir", "Jammu"),
    "srinagar": ("Jammu and Kashmir", "Srinagar"),
    "katra": ("Jammu and Kashmir", None),
    "awantipora": ("Jammu and Kashmir", None),
    "udhampur": ("Jammu and Kashmir", "Udhampur"),
    "ramban": ("Jammu and Kashmir", "Ramban"),
    "banihal": ("Jammu and Kashmir", None),
    "kishtwar": ("Jammu and Kashmir", "Kishtwar"),
    "baramulla": ("Jammu and Kashmir", "Baramulla"),
    "handwara": ("Jammu and Kashmir", None),
    "kupwara": ("Jammu and Kashmir", "Kupwara"),
    "samba": ("Jammu and Kashmir", "Samba"),
    "reasi": ("Jammu and Kashmir", "Reasi"),
    "kathua": ("Jammu and Kashmir", "Kathua"),
    "akhnoor": ("Jammu and Kashmir", None),
    "nagrota": ("Jammu and Kashmir", None),
    "doda": ("Jammu and Kashmir", "Doda"),
    "pulwama": ("Jammu and Kashmir", "Pulwama"),
    "anantnag": ("Jammu and Kashmir", "Anantnag"),
    "kulgam": ("Jammu and Kashmir", "Kulgam"),
    # Ladakh
    "leh": ("Ladakh", "Leh"),
    "kargil": ("Ladakh", "Kargil"),
    # Karnataka
    "bangalore": ("Karnataka", "Bengaluru"),
    "bengaluru": ("Karnataka", "Bengaluru"),
    "mysuru": ("Karnataka", "Mysuru"),
    "hubli": ("Karnataka", None),
    "belagavi": ("Karnataka", "Belagavi"),
    "belgaum": ("Karnataka", "Belagavi"),
    "dharwad": ("Karnataka", "Dharwad"),
    "mangaluru": ("Karnataka", None),
    "mangalore": ("Karnataka", None),
    "gulbarga": ("Karnataka", "Kalaburagi"),
    "kalaburagi": ("Karnataka", "Kalaburagi"),
    "bellary": ("Karnataka", "Ballari"),
    "davanagere": ("Karnataka", "Davanagere"),
    "shivamogga": ("Karnataka", "Shivamogga"),
    "shimoga": ("Karnataka", "Shivamogga"),
    "tumkur": ("Karnataka", "Tumakuru"),
    "hassan": ("Karnataka", "Hassan"),
    "bidar": ("Karnataka", "Bidar"),
    "raichur": ("Karnataka", "Raichur"),
    "kolar": ("Karnataka", "Kolar"),
    "baiyyappanahalli": ("Karnataka", None),
    "chitradurga": ("Karnataka", "Chitradurga"),
    "koppal": ("Karnataka", "Koppal"),
    "gadag": ("Karnataka", "Gadag"),
    "haveri": ("Karnataka", "Haveri"),
    "bagalkot": ("Karnataka", "Bagalkot"),
    "udupi": ("Karnataka", "Udupi"),
    "mandya": ("Karnataka", "Mandya"),
    "karkala": ("Karnataka", None),
    "hungund": ("Karnataka", None),
    "hoskote": ("Karnataka", None),
    "channarayapatna": ("Karnataka", None),
    # Kerala
    "kochi": ("Kerala", None),
    "kozhikode": ("Kerala", "Kozhikode"),
    "calicut": ("Kerala", "Kozhikode"),
    "kollam": ("Kerala", "Kollam"),
    "kannur": ("Kerala", "Kannur"),
    "thrissur": ("Kerala", "Thrissur"),
    "palakkad": ("Kerala", "Palakkad"),
    "thiruvananthapuram": ("Kerala", "Thiruvananthapuram"),
    "alappuzha": ("Kerala", "Alappuzha"),
    "kasaragod": ("Kerala", "Kasaragod"),
    "malappuram": ("Kerala", "Malappuram"),
    "kottayam": ("Kerala", "Kottayam"),
    "ernakulam": ("Kerala", "Ernakulam"),
    "wayanad": ("Kerala", "Wayanad"),
    "idukki": ("Kerala", "Idukki"),
    # Madhya Pradesh
    "bhopal": ("Madhya Pradesh", "Bhopal"),
    "indore": ("Madhya Pradesh", "Indore"),
    "jabalpur": ("Madhya Pradesh", "Jabalpur"),
    "gwalior": ("Madhya Pradesh", "Gwalior"),
    "ujjain": ("Madhya Pradesh", "Ujjain"),
    "rewa": ("Madhya Pradesh", "Rewa"),
    "satna": ("Madhya Pradesh", "Satna"),
    "vidisha": ("Madhya Pradesh", "Vidisha"),
    "betul": ("Madhya Pradesh", "Betul"),
    "harda": ("Madhya Pradesh", "Harda"),
    "shahdol": ("Madhya Pradesh", "Shahdol"),
    "mandla": ("Madhya Pradesh", "Mandla"),
    "mandsaur": ("Madhya Pradesh", "Mandsaur"),
    "singrauli": ("Madhya Pradesh", "Singrauli"),
    "balaghat": ("Madhya Pradesh", "Balaghat"),
    "chhindwara": ("Madhya Pradesh", "Chhindwara"),
    "seoni": ("Madhya Pradesh", "Seoni"),
    "guna": ("Madhya Pradesh", "Guna"),
    "shivpuri": ("Madhya Pradesh", "Shivpuri"),
    "damoh": ("Madhya Pradesh", "Damoh"),
    "katni": ("Madhya Pradesh", "Katni"),
    "sidhi": ("Madhya Pradesh", "Sidhi"),
    "burhanpur": ("Madhya Pradesh", "Burhanpur"),
    "dewas": ("Madhya Pradesh", "Dewas"),
    "dhar": ("Madhya Pradesh", "Dhar"),
    "jhabua": ("Madhya Pradesh", None),
    "alirajpur": ("Madhya Pradesh", "Alirajpur"),
    "neemuch": ("Madhya Pradesh", "Neemuch"),
    "ratlam": ("Madhya Pradesh", "Ratlam"),
    # Maharashtra
    "mumbai": ("Maharashtra", "Mumbai"),
    "navi mumbai": ("Maharashtra", None),
    "pune": ("Maharashtra", "Pune"),
    "nagpur": ("Maharashtra", "Nagpur"),
    "nashik": ("Maharashtra", "Nashik"),
    "aurangabad": ("Maharashtra", "Aurangabad"),
    "solapur": ("Maharashtra", "Solapur"),
    "kolhapur": ("Maharashtra", "Kolhapur"),
    "satara": ("Maharashtra", "Satara"),
    "ratnagiri": ("Maharashtra", "Ratnagiri"),
    "thane": ("Maharashtra", "Thane"),
    "sangli": ("Maharashtra", "Sangli"),
    "jalgaon": ("Maharashtra", "Jalgaon"),
    "akola": ("Maharashtra", "Akola"),
    "amravati": ("Maharashtra", "Amravati"),
    "wardha": ("Maharashtra", "Wardha"),
    "latur": ("Maharashtra", "Latur"),
    "parbhani": ("Maharashtra", "Parbhani"),
    "nanded": ("Maharashtra", "Nanded"),
    "osmanabad": ("Maharashtra", "Osmanabad"),
    "dhule": ("Maharashtra", "Dhule"),
    "jalna": ("Maharashtra", "Jalna"),
    "sindhudurg": ("Maharashtra", None),
    "gondia": ("Maharashtra", "Gondia"),
    "chandrapur": ("Maharashtra", "Chandrapur"),
    "gadchiroli": ("Maharashtra", "Gadchiroli"),
    "bhandara": ("Maharashtra", "Bhandara"),
    "buldhana": ("Maharashtra", "Buldhana"),
    "beed": ("Maharashtra", "Beed"),
    "hingoli": ("Maharashtra", "Hingoli"),
    "yavatmal": ("Maharashtra", "Yavatmal"),
    "palghar": ("Maharashtra", "Palghar"),
    "raigad": ("Maharashtra", None),
    "panvel": ("Maharashtra", None),
    "baramati": ("Maharashtra", None),
    "indapur": ("Maharashtra", None),
    "shirwal": ("Maharashtra", None),
    "lonand": ("Maharashtra", None),
    "phaltan": ("Maharashtra", None),
    "tasgaon": ("Maharashtra", None),
    "dahiwadi": ("Maharashtra", None),
    "katraj": ("Maharashtra", None),
    "talegaon": ("Maharashtra", None),
    "shikrapur": ("Maharashtra", None),
    "guhagar": ("Maharashtra", None),
    "mangaon": ("Maharashtra", None),
    "sironcha": ("Maharashtra", None),
    "manmad": ("Maharashtra", None),
    "parli": ("Maharashtra", None),
    # Manipur (incl. OCR typo "lmphal")
    "imphal": ("Manipur", None),
    "lmphal": ("Manipur", None),
    "churachandpur": ("Manipur", "Churachandpur"),
    "ukhrul": ("Manipur", "Ukhrul"),
    "tamenglong": ("Manipur", "Tamenglong"),
    "bishnupur": ("Manipur", "Bishnupur"),
    # Meghalaya
    "shillong": ("Meghalaya", None),
    "tura": ("Meghalaya", None),
    "sohra": ("Meghalaya", None),
    "dawki": ("Meghalaya", None),
    # Mizoram
    "aizawl": ("Mizoram", "Aizawl"),
    "kolasib": ("Mizoram", "Kolasib"),
    "sairang": ("Mizoram", None),
    "lengpui": ("Mizoram", None),
    "lunglei": ("Mizoram", "Lunglei"),
    "lawngtlai": ("Mizoram", "Lawngtlai"),
    "champhai": ("Mizoram", "Champhai"),
    "serchhip": ("Mizoram", "Serchhip"),
    "mamit": ("Mizoram", "Mamit"),
    # Nagaland
    "kohima": ("Nagaland", "Kohima"),
    "dimapur": ("Nagaland", "Dimapur"),
    "peren": ("Nagaland", "Peren"),
    "mokokchung": ("Nagaland", "Mokokchung"),
    "wokha": ("Nagaland", "Wokha"),
    "tuensang": ("Nagaland", "Tuensang"),
    "zunheboto": ("Nagaland", "Zunheboto"),
    # Odisha
    "bhubaneswar": ("Odisha", None),
    "cuttack": ("Odisha", "Cuttack"),
    "rourkela": ("Odisha", None),
    "sambalpur": ("Odisha", "Sambalpur"),
    "angul": ("Odisha", "Angul"),
    "talcher": ("Odisha", None),
    "paradip": ("Odisha", None),
    "paradeep": ("Odisha", None),
    "bhadrak": ("Odisha", "Bhadrak"),
    "puri": ("Odisha", "Puri"),
    "balasore": ("Odisha", "Balasore"),
    "baripada": ("Odisha", None),
    "berhampur": ("Odisha", None),
    "koraput": ("Odisha", "Koraput"),
    "jeypore": ("Odisha", None),
    "rayagada": ("Odisha", "Rayagada"),
    "bolangir": ("Odisha", "Bolangir"),
    "kendujhar": ("Odisha", "Kendujhar"),
    "nayagarh": ("Odisha", "Nayagarh"),
    "kandhamal": ("Odisha", "Kandhamal"),
    "boudh": ("Odisha", "Boudh"),
    "gajapati": ("Odisha", None),
    "duburi": ("Odisha", None),
    "chandikhole": ("Odisha", None),
    "banarpal": ("Odisha", None),
    "dhamra": ("Odisha", None),
    # Puducherry
    "puducherry": ("Puducherry", None),
    "pondicherry": ("Puducherry", None),
    "karaikal": ("Puducherry", "Karaikal"),
    # Punjab
    "amritsar": ("Punjab", "Amritsar"),
    "bathinda": ("Punjab", "Bathinda"),
    "bhatinda": ("Punjab", "Bathinda"),
    "ludhiana": ("Punjab", "Ludhiana"),
    "jalandhar": ("Punjab", "Jalandhar"),
    "patiala": ("Punjab", "Patiala"),
    "fazilka": ("Punjab", "Fazilka"),
    "gurdaspur": ("Punjab", "Gurdaspur"),
    "hoshiarpur": ("Punjab", "Hoshiarpur"),
    "kapurthala": ("Punjab", "Kapurthala"),
    "moga": ("Punjab", "Moga"),
    "abohar": ("Punjab", None),
    "sirhind": ("Punjab", None),
    "batala": ("Punjab", None),
    "rupnagar": ("Punjab", "Rupnagar"),
    "phagwara": ("Punjab", None),
    "pathankot": ("Punjab", "Pathankot"),
    "muktsar": ("Punjab", "Muktsar"),
    "sangrur": ("Punjab", "Sangrur"),
    "barnala": ("Punjab", "Barnala"),
    "firozpur": ("Punjab", "Firozpur"),
    # Rajasthan
    "jaipur": ("Rajasthan", "Jaipur"),
    "jodhpur": ("Rajasthan", "Jodhpur"),
    "udaipur": ("Rajasthan", "Udaipur"),
    "kota": ("Rajasthan", "Kota"),
    "bikaner": ("Rajasthan", "Bikaner"),
    "ajmer": ("Rajasthan", "Ajmer"),
    "bundi": ("Rajasthan", "Bundi"),
    "nagaur": ("Rajasthan", "Nagaur"),
    "jalore": ("Rajasthan", "Jalore"),
    "hanumangarh": ("Rajasthan", "Hanumangarh"),
    "nathdwara": ("Rajasthan", None),
    "beawar": ("Rajasthan", None),
    "sanchore": ("Rajasthan", None),
    "balotra": ("Rajasthan", None),
    "kherwara": ("Rajasthan", None),
    "sikar": ("Rajasthan", "Sikar"),
    "alwar": ("Rajasthan", "Alwar"),
    "bharatpur": ("Rajasthan", "Bharatpur"),
    "churu": ("Rajasthan", "Churu"),
    "jaisalmer": ("Rajasthan", "Jaisalmer"),
    "barmer": ("Rajasthan", "Barmer"),
    "tonk": ("Rajasthan", "Tonk"),
    "bhilwara": ("Rajasthan", "Bhilwara"),
    "jhalawar": ("Rajasthan", "Jhalawar"),
    "dholpur": ("Rajasthan", "Dholpur"),
    "jhunjhunu": ("Rajasthan", "Jhunjhunu"),
    "ganganagar": ("Rajasthan", "Ganganagar"),
    "dungarpur": ("Rajasthan", "Dungarpur"),
    "banswara": ("Rajasthan", "Banswara"),
    "chittorgarh": ("Rajasthan", "Chittorgarh"),
    "pali": ("Rajasthan", "Pali"),
    "karauli": ("Rajasthan", "Karauli"),
    # Sikkim
    "gangtok": ("Sikkim", "Gangtok"),
    "pakyong": ("Sikkim", "Pakyong"),
    "namchi": ("Sikkim", "Namchi"),
    "mangan": ("Sikkim", "Mangan"),
    "rangpo": ("Sikkim", None),
    "rongli": ("Sikkim", None),
    "ranipool": ("Sikkim", None),
    "singtam": ("Sikkim", None),
    "khamdong": ("Sikkim", None),
    "rhenock": ("Sikkim", None),
    # Tamil Nadu
    "chennai": ("Tamil Nadu", "Chennai"),
    "coimbatore": ("Tamil Nadu", "Coimbatore"),
    "madurai": ("Tamil Nadu", "Madurai"),
    "salem": ("Tamil Nadu", "Salem"),
    "erode": ("Tamil Nadu", "Erode"),
    "kanyakumari": ("Tamil Nadu", "Kanyakumari"),
    "hosur": ("Tamil Nadu", None),
    "sriperumbudur": ("Tamil Nadu", None),
    "arakkonam": ("Tamil Nadu", None),
    "kudankulam": ("Tamil Nadu", None),
    "ennore": ("Tamil Nadu", None),
    "vellore": ("Tamil Nadu", "Vellore"),
    "tirunelveli": ("Tamil Nadu", "Tirunelveli"),
    "thoothukudi": ("Tamil Nadu", "Thoothukudi"),
    "dindigul": ("Tamil Nadu", "Dindigul"),
    "nagercoil": ("Tamil Nadu", None),
    "kanchipuram": ("Tamil Nadu", "Kanchipuram"),
    "tiruvannamalai": ("Tamil Nadu", "Tiruvannamalai"),
    "viluppuram": ("Tamil Nadu", None),
    "nagapattinam": ("Tamil Nadu", "Nagapattinam"),
    "karur": ("Tamil Nadu", "Karur"),
    "namakkal": ("Tamil Nadu", "Namakkal"),
    "theni": ("Tamil Nadu", "Theni"),
    "sivaganga": ("Tamil Nadu", "Sivaganga"),
    "ramanathapuram": ("Tamil Nadu", "Ramanathapuram"),
    "virudhunagar": ("Tamil Nadu", "Virudhunagar"),
    "tiruppur": ("Tamil Nadu", "Tiruppur"),
    "kallakurichi": ("Tamil Nadu", "Kallakurichi"),
    "nilgiris": ("Tamil Nadu", "The Nilgiris"),
    # Telangana
    "hyderabad": ("Telangana", "Hyderabad"),
    "warangal": ("Telangana", "Warangal"),
    "khammam": ("Telangana", "Khammam"),
    "karimnagar": ("Telangana", "Karimnagar"),
    "nizamabad": ("Telangana", "Nizamabad"),
    "mahabubnagar": ("Telangana", "Mahabubnagar"),
    "medak": ("Telangana", "Medak"),
    "sangareddy": ("Telangana", "Sangareddy"),
    "nalgonda": ("Telangana", "Nalgonda"),
    "adilabad": ("Telangana", "Adilabad"),
    "rangareddy": ("Telangana", "Rangareddy"),
    "secunderabad": ("Telangana", None),
    "medchal": ("Telangana", "Medchal"),
    "godavarikhani": ("Telangana", None),
    "bibinagar": ("Telangana", None),
    "kalwakurthy": ("Telangana", None),
    # Tripura
    "agartala": ("Tripura", None),
    "kailashahar": ("Tripura", None),
    "dharmanagar": ("Tripura", None),
    "teliamura": ("Tripura", None),
    "khowai": ("Tripura", "Khowai"),
    "kamalpur": ("Tripura", None),
    # Uttar Pradesh
    "lucknow": ("Uttar Pradesh", "Lucknow"),
    "kanpur": ("Uttar Pradesh", "Kanpur"),
    "varanasi": ("Uttar Pradesh", "Varanasi"),
    "agra": ("Uttar Pradesh", "Agra"),
    "allahabad": ("Uttar Pradesh", "Prayagraj"),
    "prayagraj": ("Uttar Pradesh", "Prayagraj"),
    "meerut": ("Uttar Pradesh", "Meerut"),
    "gorakhpur": ("Uttar Pradesh", "Gorakhpur"),
    "bareilly": ("Uttar Pradesh", "Bareilly"),
    "aligarh": ("Uttar Pradesh", "Aligarh"),
    "moradabad": ("Uttar Pradesh", "Moradabad"),
    "saharanpur": ("Uttar Pradesh", "Saharanpur"),
    "shamli": ("Uttar Pradesh", "Shamli"),
    "mirzapur": ("Uttar Pradesh", "Mirzapur"),
    "ghazipur": ("Uttar Pradesh", "Ghazipur"),
    "ballia": ("Uttar Pradesh", "Ballia"),
    "hardoi": ("Uttar Pradesh", "Hardoi"),
    "sitapur": ("Uttar Pradesh", "Sitapur"),
    "bahraich": ("Uttar Pradesh", "Bahraich"),
    "shravasti": ("Uttar Pradesh", "Shravasti"),
    "deoria": ("Uttar Pradesh", "Deoria"),
    "ayodhya": ("Uttar Pradesh", "Ayodhya"),
    "faizabad": ("Uttar Pradesh", "Ayodhya"),
    "raebareli": ("Uttar Pradesh", "Raebareli"),
    "etawah": ("Uttar Pradesh", "Etawah"),
    "amethi": ("Uttar Pradesh", "Amethi"),
    "pratapgarh": ("Uttar Pradesh", "Pratapgarh"),
    "mathura": ("Uttar Pradesh", "Mathura"),
    "noida": ("Uttar Pradesh", None),
    "mughalsarai": ("Uttar Pradesh", None),
    "khalilabad": ("Uttar Pradesh", None),
    "gonda": ("Uttar Pradesh", "Gonda"),
    "basti": ("Uttar Pradesh", "Basti"),
    "siddharthnagar": ("Uttar Pradesh", "Siddharth Nagar"),
    "jhansi": ("Uttar Pradesh", "Jhansi"),
    "etah": ("Uttar Pradesh", "Etah"),
    "hathras": ("Uttar Pradesh", "Hathras"),
    "mainpuri": ("Uttar Pradesh", "Mainpuri"),
    "firozabad": ("Uttar Pradesh", "Firozabad"),
    "baghpat": ("Uttar Pradesh", "Baghpat"),
    "bulandshahr": ("Uttar Pradesh", "Bulandshahr"),
    "budaun": ("Uttar Pradesh", "Budaun"),
    "shahjahanpur": ("Uttar Pradesh", "Shahjahanpur"),
    "pilibhit": ("Uttar Pradesh", "Pilibhit"),
    "lalitpur": ("Uttar Pradesh", "Lalitpur"),
    "chitrakoot": ("Uttar Pradesh", "Chitrakoot"),
    "banda": ("Uttar Pradesh", "Banda"),
    "mahoba": ("Uttar Pradesh", "Mahoba"),
    "jalaun": ("Uttar Pradesh", "Jalaun"),
    "sonbhadra": ("Uttar Pradesh", "Sonbhadra"),
    "chandauli": ("Uttar Pradesh", "Chandauli"),
    "jaunpur": ("Uttar Pradesh", "Jaunpur"),
    "kushinagar": ("Uttar Pradesh", "Kushinagar"),
    "azamgarh": ("Uttar Pradesh", "Azamgarh"),
    "fatehpur": ("Uttar Pradesh", "Fatehpur"),
    "unnao": ("Uttar Pradesh", "Unnao"),
    "barabanki": ("Uttar Pradesh", "Barabanki"),
    "najibabad": ("Uttar Pradesh", None),
    "jewar": ("Uttar Pradesh", None),
    # Uttarakhand
    "dehradun": ("Uttarakhand", "Dehradun"),
    "haridwar": ("Uttarakhand", "Haridwar"),
    "rishikesh": ("Uttarakhand", None),
    "roorkee": ("Uttarakhand", None),
    "nainital": ("Uttarakhand", "Nainital"),
    "haldwani": ("Uttarakhand", None),
    "kashipur": ("Uttarakhand", None),
    "almora": ("Uttarakhand", "Almora"),
    "pauri": ("Uttarakhand", None),
    "rudraprayag": ("Uttarakhand", "Rudraprayag"),
    "tehri": ("Uttarakhand", None),
    "uttarkashi": ("Uttarakhand", "Uttarkashi"),
    "champawat": ("Uttarakhand", "Champawat"),
    "pithoragarh": ("Uttarakhand", "Pithoragarh"),
    "bageshwar": ("Uttarakhand", "Bageshwar"),
    "joshimath": ("Uttarakhand", None),
    # West Bengal
    "kolkata": ("West Bengal", "Kolkata"),
    "siliguri": ("West Bengal", None),
    "darjeeling": ("West Bengal", "Darjeeling"),
    "durgapur": ("West Bengal", None),
    "asansol": ("West Bengal", None),
    "kharagpur": ("West Bengal", None),
    "haldia": ("West Bengal", None),
    "bankura": ("West Bengal", "Bankura"),
    "purulia": ("West Bengal", "Purulia"),
    "malda": ("West Bengal", "Malda"),
    "maldah": ("West Bengal", "Malda"),
    "murshidabad": ("West Bengal", "Murshidabad"),
    "nadia": ("West Bengal", "Nadia"),
    "howrah": ("West Bengal", "Howrah"),
    "hooghly": ("West Bengal", "Hooghly"),
    "medinipur": ("West Bengal", None),
    "mednipore": ("West Bengal", None),
    "bagdogra": ("West Bengal", None),
    "sainthia": ("West Bengal", None),
    "sitarampur": ("West Bengal", None),
    "raniganj": ("West Bengal", None),
    "farakka": ("West Bengal", None),
    "alipurduar": ("West Bengal", "Alipurduar"),
    "cooch behar": ("West Bengal", "Cooch Behar"),
    "jhargram": ("West Bengal", "Jhargram"),
}


_REGEX_CACHE: dict[str, re.Pattern] = {}


def _regex_for(token: str) -> re.Pattern:
    pattern = _REGEX_CACHE.get(token)
    if pattern is None:
        if " " in token:
            pattern = re.compile(re.escape(token))
        else:
            pattern = re.compile(r"(?<![a-z])" + re.escape(token) + r"(?![a-z])")
        _REGEX_CACHE[token] = pattern
    return pattern


def detect_location(name: str | None) -> tuple[str, str]:
    """Return (state, district) derived conservatively from a project name."""
    lower = (name or "").lower()

    states: set[str] = set()
    matched_places: list[tuple[str, str, str | None]] = []

    for alias, canonical in STATE_ALIASES.items():
        if _regex_for(alias).search(lower):
            states.add(canonical)

    for token, (canonical, district) in PLACES.items():
        if _regex_for(token).search(lower):
            states.add(canonical)
            matched_places.append((token, canonical, district))

    if len(states) != 1:
        return UNSPECIFIED, UNSPECIFIED

    state = next(iter(states))
    if len(matched_places) == 1:
        _token, place_state, district = matched_places[0]
        if district and place_state == state:
            return state, district
    return state, UNSPECIFIED