--Projects table for the database

CREATE TABLE IF NOT EXISTS projects (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(100) NOT NULL,
    ministry VARCHAR(150) NOT NULL,
    state VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    sanctioned_cost DOUBLE PRECISION NOT NULL CHECK (sanctioned_cost >= 0),
    revised_cost DOUBLE PRECISION CHECK (revised_cost IS NULL OR revised_cost >= 0),
    start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    current_status VARCHAR(50) NOT NULL,
    category VARCHAR(100) NOT NULL,
    size_bucket VARCHAR(50) NOT NULL,
    CONSTRAINT projects_date_order_chk CHECK (planned_end_date >= start_date)
);

-- milestones table

CREATE TABLE IF NOT EXISTS milestones (
    milestone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    planned_date DATE NOT NULL,
    actual_date DATE,
    status VARCHAR(50) NOT NULL,
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    dependency_milestone_id INTEGER REFERENCES milestones(milestone_id) ON DELETE SET NULL,
    CONSTRAINT milestones_dependency_not_self_chk
        CHECK (dependency_milestone_id IS NULL OR dependency_milestone_id <> milestone_id)
);

--progress_report table

CREATE TABLE IF NOT EXISTS progress_reports (
    report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    physical_progress_pct DOUBLE PRECISION NOT NULL CHECK (physical_progress_pct >= 0 AND physical_progress_pct <= 100),
    expenditure_cumulative DOUBLE PRECISION NOT NULL CHECK (expenditure_cumulative >= 0),
    remarks TEXT
);

--risk_scores tables

CREATE TABLE IF NOT EXISTS risk_scores (
    score_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    computed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    health_score DOUBLE PRECISION NOT NULL CHECK (health_score >= 0 AND health_score <= 100),
    delay_probability DOUBLE PRECISION NOT NULL CHECK (delay_probability >= 0 AND delay_probability <= 1),
    -- Percentage cost escalation estimate, matching the PRAGATI-AI model target.
    cost_overrun_estimate DOUBLE PRECISION NOT NULL CHECK (cost_overrun_estimate >= 0),
    component_breakdown JSON NOT NULL
);

--alerts_table

CREATE TABLE IF NOT EXISTS alerts (
    alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    explanation_text TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN'
);

--users table

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(100) NOT NULL,
    ministry_scope VARCHAR(150),
    state_scope VARCHAR(100),
    email VARCHAR(255) NOT NULL UNIQUE
);

--iinterventions table

CREATE TABLE IF NOT EXISTS interventions (
    intervention_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id INTEGER NOT NULL REFERENCES alerts(alert_id) ON DELETE CASCADE,
    assigned_to VARCHAR(150),
    action_taken TEXT NOT NULL,
    action_date DATE NOT NULL,
    outcome_status VARCHAR(50) NOT NULL,
    outcome_recorded_at TIMESTAMP
);

--audit_log table

CREATE TABLE IF NOT EXISTS audit_log (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    action_type VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSON
);

