--Projects table for the database

CREATE TABLE IF NOT EXISTS projects (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(100) NOT NULL,
    ministry VARCHAR(150) NOT NULL,
    state VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    sanctioned_cost DOUBLE PRECISION NOT NULL CHECK (sanctioned_cost >= 0),
    revised_cost DOUBLE PRECISION CHECK (revised_cost IS NULL OR revised_cost >= 0),
    start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    current_status VARCHAR(50) NOT NULL,
    category VARCHAR(100) NOT NULL,
    size_bucket VARCHAR(50) NOT NULL,
    CONSTRAINT projects_date_order_chk CHECK (planned_end_date >= start_date)
);