--PROJECTS table

CREATE TABLE IF NOT EXISTS projects (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sector VARCHAR(100) NOT NULL,
    ministry VARCHAR(150) NOT NULL,
    state VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    sanctioned_cost NUMERIC(18,2) NOT NULL CHECK (sanctioned_cost > 0),
    revised_cost NUMERIC(18,2) CHECK (revised_cost IS NULL OR revised_cost >= sanctioned_cost),
    start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    current_status VARCHAR(50) NOT NULL CHECK (current_status IN ('PLANNING','IN_PROGRESS','DELAYED','COMPLETED','ON_HOLD')),
    category VARCHAR(100) NOT NULL,
    size_bucket VARCHAR(20) GENERATED ALWAYS AS (
        CASE WHEN sanctioned_cost < 500 THEN 'SMALL'
             WHEN sanctioned_cost < 1000 THEN 'MEDIUM'
             ELSE 'LARGE' END
    ) STORED,
    CONSTRAINT projects_date_order_chk CHECK (planned_end_date >= start_date)
);

--MILESTONES table

CREATE TABLE IF NOT EXISTS milestones (
    milestone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    name VARCHAR(255) NOT NULL,
    planned_date DATE NOT NULL,
    actual_date DATE,
    status VARCHAR(50) NOT NULL CHECK (status IN ('PLANNED','IN_PROGRESS','COMPLETED','DELAYED','CANCELLED')),
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    dependency_milestone_id INTEGER REFERENCES milestones(milestone_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT milestones_dependency_not_self_chk CHECK (dependency_milestone_id IS NULL OR dependency_milestone_id <> milestone_id),
    CONSTRAINT milestones_actual_date_chk CHECK (actual_date IS NULL OR actual_date >= planned_date)
);

--PROGRESS_REPORTS table

CREATE TABLE IF NOT EXISTS progress_reports (
    report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    report_date DATE NOT NULL,
    physical_progress_pct NUMERIC(5,2) NOT NULL CHECK (physical_progress_pct BETWEEN 0 AND 100),
    expenditure_cumulative NUMERIC(18,2) NOT NULL CHECK (expenditure_cumulative >= 0),
    remarks TEXT,
    CONSTRAINT progress_reports_project_date_uq UNIQUE (project_id, report_date)
);

--RISK_SCORES table

CREATE TABLE IF NOT EXISTS risk_scores (
    score_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    computed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    health_score NUMERIC(5,2) NOT NULL CHECK (health_score BETWEEN 0 AND 100),
    delay_probability NUMERIC(5,4) NOT NULL CHECK (delay_probability BETWEEN 0 AND 1),
    cost_overrun_estimate NUMERIC(18,2) NOT NULL CHECK (cost_overrun_estimate >= 0),
    component_breakdown JSONB NOT NULL
);

--ALERTS table

CREATE TABLE IF NOT EXISTS alerts (
    alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(project_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW')),
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    explanation_text TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED'))
);

--USERS table

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(100) NOT NULL,
    ministry_scope VARCHAR(150),
    state_scope VARCHAR(100),
    email VARCHAR(255) NOT NULL UNIQUE
);

--INTERVENTIONS table

CREATE TABLE IF NOT EXISTS interventions (
    intervention_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id INTEGER NOT NULL REFERENCES alerts(alert_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    assigned_to VARCHAR(150),
    action_taken TEXT NOT NULL,
    action_date DATE NOT NULL,
    outcome_status VARCHAR(50) NOT NULL CHECK (outcome_status IN ('PENDING','IN_PROGRESS','COMPLETED','UNSUCCESSFUL')),
    outcome_recorded_at TIMESTAMP,
    CONSTRAINT intervention_outcome_date_chk CHECK (outcome_recorded_at IS NULL OR outcome_recorded_at >= action_date::timestamp)
);

--AUDIT_LOG table

CREATE TABLE IF NOT EXISTS audit_log (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    action_type VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id INTEGER NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB
);

-- Indexes used for queries

CREATE INDEX IF NOT EXISTS idx_milestones_project_id ON milestones(project_id);
CREATE INDEX IF NOT EXISTS idx_milestones_dependency_id ON milestones(dependency_milestone_id);
CREATE INDEX IF NOT EXISTS idx_progress_reports_project_id ON progress_reports(project_id);
CREATE INDEX IF NOT EXISTS idx_risk_scores_project_id ON risk_scores(project_id);
CREATE INDEX IF NOT EXISTS idx_alerts_project_id ON alerts(project_id);
CREATE INDEX IF NOT EXISTS idx_interventions_alert_id ON interventions(alert_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);

-- Common filter/search paths.
CREATE INDEX IF NOT EXISTS idx_projects_sector ON projects(sector);
CREATE INDEX IF NOT EXISTS idx_projects_ministry ON projects(ministry);
CREATE INDEX IF NOT EXISTS idx_projects_state ON projects(state);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(current_status);
CREATE INDEX IF NOT EXISTS idx_projects_state_sector ON projects(state, sector);
CREATE INDEX IF NOT EXISTS idx_progress_project_date ON progress_reports(project_id, report_date DESC);
CREATE INDEX IF NOT EXISTS idx_risk_project_computed ON risk_scores(project_id, computed_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_computed_at ON risk_scores(computed_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_delay_probability ON risk_scores(delay_probability DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity_status ON alerts(severity, status);
CREATE INDEX IF NOT EXISTS idx_alerts_generated_at ON alerts(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_project_generated ON alerts(project_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_interventions_outcome_status ON interventions(outcome_status);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user_time ON audit_log(user_id, timestamp DESC);

-- A project_overview that shows core details and most recent data 
CREATE OR REPLACE VIEW project_overview AS
SELECT p.project_id, p.name, p.sector, p.ministry, p.state, p.district,
       p.sanctioned_cost, p.revised_cost, p.start_date, p.planned_end_date,
       p.current_status, p.category, p.size_bucket,
       pr.report_date AS latest_report_date,
       pr.physical_progress_pct AS latest_physical_progress_pct,
       pr.expenditure_cumulative AS latest_expenditure_cumulative,
       rs.computed_at AS latest_risk_computed_at,
       rs.health_score AS latest_health_score,
       rs.delay_probability AS latest_delay_probability,
       rs.cost_overrun_estimate AS latest_cost_overrun_estimate,
       rs.component_breakdown AS latest_component_breakdown
FROM projects p
LEFT JOIN LATERAL (
    SELECT * FROM progress_reports x WHERE x.project_id = p.project_id
    ORDER BY x.report_date DESC LIMIT 1
) pr ON TRUE
LEFT JOIN LATERAL (
    SELECT * FROM risk_scores x WHERE x.project_id = p.project_id
    ORDER BY x.computed_at DESC LIMIT 1
) rs ON TRUE;